#!/bin/sh

set -e

PREREQ=""

prereqs () {
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

. /usr/share/initramfs-tools/hook-functions

manual_add_modules bridge
manual_add_modules bonding

if [ -x /sbin/brctl ]; then
    copy_exec /sbin/brctl /sbin
fi

if [ -x /sbin/ifenslave ]; then
    copy_exec /sbin/ifenslave /sbin
fi

exit 0
