#!/bin/sh

set -e

PREREQ=""

prereqs () {
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /lib/*-linux-gnu/libnss_dns* /lib
echo 'hosts: files dns' >> ${DESTDIR}/etc/nsswitch.conf

exit 0
