#!/bin/sh

set -e

boot_iface=${1}
if [ -n "${boot_iface}" ]; then

    # bridge.
    #/sbin/brctl addbr br0 > /dev/null
    #/sbin/brctl addif br0 ${boot_iface} > /dev/null
    #/sbin/ifconfig br0 up > /dev/null
    #/sbin/ifconfig ${boot_iface} up 0.0.0.0 > /dev/null
    #/bin/ipconfig -t 20 br0 > /dev/null
    #echo br0

    # bonding.
    #/sbin/modprobe bonding > /dev/null
    #/sbin/ifenslave bond0 ${boot_iface} > /dev/null
    #/sbin/ifconfig bond0 up > /dev/null
    #/sbin/ifconfig ${boot_iface} up 0.0.0.0 > /dev/null
    #/bin/ipconfig -t 20 bond0 > /dev/null
    #echo bond0

    # bonding + bridge.
    #/sbin/modprobe bonding > /dev/null
    #/sbin/ifenslave bond0 ${boot_iface} > /dev/null
    #/sbin/ifconfig bond0 up > /dev/null
    #/sbin/ifconfig ${boot_iface} up 0.0.0.0 > /dev/null
    #/sbin/brctl addbr br0 > /dev/null
    #/sbin/brctl addif br0 bond0 > /dev/null
    #/sbin/ifconfig bond0 up 0.0.0.0 > /dev/null
    #/bin/ipconfig -t 20 br0 > /dev/null
    #echo br0

    exit 0

fi

exit 0
