#!/bin/sh

interface=${1}
ip_address=$(ip -4 addr show "${interface}" | awk '/.* inet .+/ {print $2}' | head -n 1)

if [ -n "${ip_address}" ]; then

    ICOLOR=$(tput -Tlinux setaf 2)
    NCOLOR=$(tput -Tlinux setaf 9)
    TITLE="${interface}: ""${ICOLOR}""${ip_address}""${NCOLOR}"
    
    sed -i "s/^${interface}:.*/${TITLE}/g" /etc/issue

else

    sed -i "/^${interface}:.*/ d" /etc/issue

fi
